name: auto update

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 * * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependence
        run: npm i -g pnpm && pnpm i --no-frozen-lockfile

      - name: generate RSS
        run: npm run rss

      - name: commit the all info
        run: |
          git config --global user.email "eyelly.wu@gmail.com"
          git config --global user.name "Eyelly Wu"
          git add .
          git commit -m 'chore: automatic update of GitHub workflow'

      - name: git push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
